name: Release

on:
  release:
    types:
      - created

jobs:
  dist:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          cd $GITHUB_WORKSPACE
          yarn install
      - name: Build
        run: yarn build

      - name: Upload
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/dialogflow-chat-widget.js
          asset_name: dialogflow-chat-widget.js
          asset_content_type: application/javascript

      - name: Upload minified
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/dialogflow-chat-widget.min.js
          asset_name: dialogflow-chat-widget.min.js
          asset_content_type: application/javascript
